steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/siraj:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/siraj:$COMMIT_SHA']

  # Deploy to Cloud Run (US region)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - run
      - deploy
      - siraj
      - --image
      - gcr.io/$PROJECT_ID/siraj:$COMMIT_SHA
      - --region
      - us-central1
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-env-vars
      - NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY},NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN},NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID},NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET},NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID},NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID},NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}

  # 1) Capture the exact image the US service is running
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Capture image digest from US
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        IMAGE="$(gcloud run services describe siraj --region=us-central1 \
          --format='value(spec.template.spec.containers[0].image)')"
        echo "IMAGE=${IMAGE}" | tee image.env

  # 2) Roll EU to the exact same image (parity)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy EU same image
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        source image.env
        gcloud run services update siraj-eu --region=europe-west1 --image "$IMAGE" --quiet

  # 3) Invalidate CDN cache
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Invalidate CDN
    entrypoint: bash
    args: [ "-lc", "gcloud compute url-maps invalidate-cdn-cache siraj-web-map --path '/*' --quiet" ]

  # 4) Verify origins & CDN (scripts you added)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Verify origins + CDN
    entrypoint: bash
    args: [ "-lc", "./scripts/verify-origins.sh && ./scripts/cdn-parity.sh" ]

substitutions:
  _URL_MAP: siraj-web-map
  _SERVICE_US: siraj
  _SERVICE_EU: siraj-eu
  _REGION_US: us-central1
  _REGION_EU: europe-west1

images:
  - 'gcr.io/$PROJECT_ID/siraj:$COMMIT_SHA'
