steps:
  # Step 1: Build the Docker image with Firebase build args
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/web:$SHORT_SHA'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyBlAiqH3HaLcgq6ZFqkXrA6WPcGx-EchC4'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=walduae-project-20250809071906.firebaseapp.com'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=walduae-project-20250809071906'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=walduae-project-20250809071906.firebasestorage.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=207501673877'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=1:207501673877:web:8c8265c153623cf14ae29c'
      - '.'

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/web:$SHORT_SHA'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'siraj'
      - '--image'
      - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/web:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '2'
      - '--max-instances'
      - '100'
      - '--concurrency'
      - '80'
      - '--cpu'
      - '1'
      - '--memory'
      - '512Mi'
      - '--timeout'
      - '60s'
      - '--cpu-boost'

# Substitutions for flexibility
substitutions:
  _LOCATION: us-central1
  _REPOSITORY: siraj

# Images to be pushed to registry
images:
  - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/web:$SHORT_SHA'

# Build configuration
options:
  machineType: E2_STANDARD_4
  substitution_option: ALLOW_LOOSE
