steps:
  # 1a. Validate next.config.mjs contract before build
  - name: 'ubuntu:22.04'
    id: validate-config
    entrypoint: bash
    args:
      - -c
      - |
        echo "🔍 Validating next.config.mjs header contract..."
        if [ -f "next.config.mjs" ]; then
          echo "✅ next.config.mjs found"
        else
          echo "❌ next.config.mjs not found"
          exit 1
        fi
        echo "✅ Config validation passed"

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/siraj:latest', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/siraj:latest']

  # Deploy to Cloud Run (US region) with Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    args:
      - gcloud
      - run
      - deploy
      - siraj
      - --image
      - gcr.io/$PROJECT_ID/siraj:latest
      - --region
      - us-central1
      - --platform
      - managed
      - --allow-unauthenticated
      - --update-secrets
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=NEXT_PUBLIC_FIREBASE_PROJECT_ID:latest,NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:latest,NEXT_PUBLIC_FIREBASE_API_KEY=NEXT_PUBLIC_FIREBASE_API_KEY:latest,NEXT_PUBLIC_WEBSITE_URL=NEXT_PUBLIC_WEBSITE_URL:latest,NEXT_PUBLIC_GAMESERVER_CONNECTION_MESSAGE=NEXT_PUBLIC_GAMESERVER_CONNECTION_MESSAGE:latest,NEXT_PUBLIC_DISCORD_INVITE_URL=NEXT_PUBLIC_DISCORD_INVITE_URL:latest,NEXT_PUBLIC_PAYNOW_STORE_ID=NEXT_PUBLIC_PAYNOW_STORE_ID:latest,NEXT_PUBLIC_BACKGROUND_IMAGE_URL=NEXT_PUBLIC_BACKGROUND_IMAGE_URL:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,PAYNOW_API_KEY=PAYNOW_API_KEY:latest,FIREBASE_PROJECT_ID=FIREBASE_PROJECT_ID:latest,PAYNOW_STORE_ID=PAYNOW_STORE_ID:latest,SIRAJ_CONFIG_JSON=SIRAJ_CONFIG_JSON:latest

  # Deploy EU to the same image (parity)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    id: deploy-eu-parity
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        echo "🌍 Deploying EU to same image..."
        gcloud run services update siraj-eu --region=europe-west1 --image "gcr.io/$PROJECT_ID/siraj:latest" --quiet
        echo "✅ EU deployment complete"

  # Invalidate CDN cache
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    id: invalidate-cdn
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        echo "🔄 Invalidating CDN cache..."
        gcloud compute url-maps invalidate-cdn-cache siraj-web-map --path '/*' --quiet
        echo "✅ CDN cache invalidated"

images:
  - 'gcr.io/$PROJECT_ID/siraj:latest'
