apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: siraj
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      containers:
      - image: gcr.io/walduae-project-20250809071906/siraj:latest
        ports:
        - containerPort: 3000
        env:
        # Path to the mounted secret file
        - name: SIRAJ_CONFIG_PATH
          value: /var/secrets/siraj/config.json
        # Keep these public env vars (safe to expose)
        - name: NODE_ENV
          value: production
        - name: NEXT_PUBLIC_FIREBASE_PROJECT_ID
          value: walduae-project-20250809071906
        - name: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
          value: siraj.life
        - name: NEXT_PUBLIC_FIREBASE_API_KEY
          value: AIzaSyBlAiqH3HaLcgq6ZFqkXrA6WPcGx-EchC4
        - name: NEXT_PUBLIC_FIREBASE_APP_ID
          value: 1:207501673877:web:8c8265c153623cf14ae29c
        - name: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
          value: "207501673877"
        - name: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
          value: walduae-project-20250809071906.appspot.com
        - name: NEXT_PUBLIC_PAYNOW_STORE_ID
          value: "321641745957789696"
        - name: NEXT_PUBLIC_BACKGROUND_IMAGE_URL
          value: https://via.placeholder.com/1920x1080/8e51ff/ffffff?text=Siraj
        - name: NEXT_PUBLIC_FEAT_POINTS
          value: "1"
        - name: NEXT_PUBLIC_PAYNOW_LIVE
          value: "1"
        # These are for local dev fallback
        - name: FEAT_POINTS
          value: "1"
        # Mount secrets as volumes
        volumeMounts:
        - name: siraj-config
          mountPath: /var/secrets/siraj
          readOnly: true
      volumes:
      # Mount the secret as a volume
      - name: siraj-config
        secret:
          secretName: siraj-config
          items:
          - key: latest
            path: config.json
