name: tRPC Post-Deploy Check

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 5 * * *' # 05:30 UTC daily (09:30 Asia/Dubai)

permissions:
  contents: read
  issues: write

concurrency:
  group: trpc-postdeploy
  cancel-in-progress: false

jobs:
  check-trpc:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run tRPC checks (with retries)
        env:
          BASE_URL: https://siraj.life
          MAX_ATTEMPTS: '30'   # ~10 min
          SLEEP_SECONDS: '20'
        run: node .github/scripts/trpc-check.mjs

      - name: Open/Update failure issue
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const title = "🚨 tRPC post-deploy check failing";
            const body = `The tRPC post-deploy workflow failed on ${new Date().toISOString()}.
            See run: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner, repo: context.repo.repo, state: "open"
            });
            const existing = issues.find(i => i.title === title);
            if (existing) {
              await github.rest.issues.createComment({
                owner: context.repo.owner, repo: context.repo.repo,
                issue_number: existing.number, body
              });
            } else {
              await github.rest.issues.create({
                owner: context.repo.owner, repo: context.repo.repo,
                title, body
              });
            }
